export const ListadoPropiedades = [
  {
    id: 1,
    title: "Casa en la playa",
    tipoMoneda: "U$D",
    precio: 1200,
    disposicion: "Frente al mar",
    tipoVenta: "Venta",
    ubicacion: "Maldonado",
    comodidades: ["Piscina", "Cocina Equipada", "Vista al mar", "Jardín"],
    descripcion: "Espectacular casa frente al mar en Punta del Este",
    aceptaMascotasOptions: "Sí",
    zona: "Punta Ballena",
    garaje: "Sí",
    m2Edificados: 400,
    m2Terreno: 1000,
    tipoDePropiedad: "Casa",
    banos: 4,
    dormitorio: "5 dormitorios",
    anioConstruccion: 2015,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/5wURoOUOnkZg2WLZ7pnCaayW-IYCyQOMv8ZvDM0FsHU/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvODQ4/NTQ5Mjg2L2VzL2Zv/dG8vc3VlJUMzJUIx/by1jYXNhLWRlLWx1/am8tY2FzYS1lbC0l/QzMlQTl4aXRvLmpw/Zz9zPTYxMng2MTIm/dz0wJms9MjAmYz1x/dl94Qm5aM2V2WmJy/NFl5dGEyYVd3RjNw/V3BZMm45a2I1OThT/cXdsdDkwPQ",

      "https://example.com/image2.jpg",
      "https://example.com/image3.jpg",
    ],
  },
  {
    id: 2,
    title: "Apartamento céntrico",
    tipoMoneda: "U$D",
    precio: 900,
    disposicion: "Interno",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: ["Aire Acondicionado", "Terraza", "Cocina Equipada"],
    descripcion: "Acogedor apartamento en pleno centro de Montevideo",
    aceptaMascotasOptions: "No",
    zona: "Centro",
    garaje: "No",
    m2Edificados: 80,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 1,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2000,
    estado: "Buen estado",
    imgsrc: [
      "https://imagenes.elpais.com/resizer/fqKCMWoK8PaHFKh2RNUfMIKMv80=/1200x675/cloudfront-eu-central-1.images.arcpublishing.com/prisa/IRBI33KR75F6RH2UZMQM4TLMFM.jpg",
      "https://example.com/image5.jpg",
      "https://example.com/image6.jpg",
    ],
  },
  {
    id: 3,
    title: "Chalet en el bosque",
    tipoMoneda: "U$D",
    precio: 1500,
    disposicion: "Bosque",
    tipoVenta: "Venta",
    ubicacion: "Lavalleja",
    comodidades: ["Piscina", "Vista al bosque", "Parque amplio"],
    descripcion:
      "Encantador chalet rodeado de naturaleza en las Sierras de Minas",
    aceptaMascotasOptions: "Sí",
    zona: "Sierras de Minas",
    garaje: "Sí",
    m2Edificados: 200,
    m2Terreno: 3000,
    tipoDePropiedad: "Casa",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 1990,
    estado: "Muy buen estado",
    imgsrc: [
      "https://assets-global.website-files.com/5f4f67c5950db17954dd4f52/5f5b7ee442f1e5b9fee1c117_hacerse-una-casa-p-1080.jpeg",
      "https://example.com/image8.jpg",
      "https://example.com/image9.jpg",
    ],
  },
  {
    id: 4,
    title: "Piso en el centro histórico",
    tipoMoneda: "U$D",
    precio: 1100,
    disposicion: "Exterior",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: ["Vista al casco antiguo", "Terraza", "Cocina moderna"],
    descripcion: "Elegante piso con vistas en el corazón de la Ciudad Vieja",
    aceptaMascotasOptions: "No",
    zona: "Ciudad Vieja",
    garaje: "No",
    m2Edificados: 120,
    m2Terreno: 0,
    tipoDePropiedad: "Piso",
    banos: 2,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2012,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/7XF0LrVsV0EVz-xssYCM_TpVkjv-3SzDfUnDMOiBo24/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9lc3Bh/Y2lvaG9nYXIuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE2/LzA0LzUwLWZvdG9z/LWZhY2hhZGFzLWNh/c2FzLW1hcy1ib25p/dGFzLW1vZGVybmFz/LWRlbC1tdW5kby1j/YXNhLWRlLWVzdGls/by1mdXR1cmlzdGEt/Y29uLWZvcm1hcy1v/dmFsYWRhcy5qcGc",
      "https://example.com/image11.jpg",
      "https://example.com/image12.jpg",
    ],
  },
  {
    id: 5,
    title: "Terreno en las afueras",
    tipoMoneda: "U$D",
    precio: 500,
    disposicion: "Rural",
    tipoVenta: "Venta",
    ubicacion: "Canelones",
    comodidades: ["Terreno amplio", "Vistas al campo"],
    descripcion: "Amplio terreno rural para construir tu casa de ensueño",
    aceptaMascotasOptions: "Sí",
    zona: "San Ramón",
    garaje: "No",
    m2Edificados: 0,
    m2Terreno: 5000,
    tipoDePropiedad: "Terreno",
    banos: 0,
    dormitorio: "0 dormitorios",
    anioConstruccion: null,
    estado: "Sin construcción",
    imgsrc: [
      "https://imgs.search.brave.com/kj8nh_53woNgna4dfe_R82iD26f_Ky7qMRtY-3LqMt8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9kZWNv/cmFpZGVhcy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMTkv/MDgvMDItNC03Njh4/NTc3LmpwZw",
      "https://example.com/image14.jpg",
      "https://example.com/image15.jpg",
    ],
  },
  {
    id: 6,
    title: "Apartamento en la costa",
    tipoMoneda: "U$D",
    precio: 950,
    disposicion: "Frente al mar",
    tipoVenta: "Alquiler",
    ubicacion: "Canelones",
    comodidades: [
      "Balcón con vistas",
      "Cocina Equipada",
      "Piscina comunitaria",
    ],
    descripcion: "Agradable apartamento con vistas al mar en Atlántida",
    aceptaMascotasOptions: "Sí",
    zona: "Atlántida",
    garaje: "Sí",
    m2Edificados: 70,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 1,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2005,
    estado: "Buen estado",
    imgsrc: [
      "https://imgs.search.brave.com/Q_o7urkviLujqL633-2RYkxHFhQ6EHJoeHuTIL7xIAE/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9lc3Bh/Y2lvaG9nYXIuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE2/LzA0LzUwLWZvdG9z/LWZhY2hhZGFzLWNh/c2FzLW1hcy1ib25p/dGFzLW1vZGVybmFz/LWRlbC1tdW5kby1p/bnNwaXJhY2lvbi1j/YWxpZm9ybmlhLmpw/Zw",
      "https://example.com/image17.jpg",
      "https://example.com/image18.jpg",
    ],
  },
  {
    id: 7,
    title: "Casa de campo",
    tipoMoneda: "U$D",
    precio: 850,
    disposicion: "Campo",
    tipoVenta: "Venta",
    ubicacion: "Tacuarembó",
    comodidades: ["Terreno amplio", "Piscina", "Parque con árboles"],
    descripcion: "Tranquila casa de campo en Tacuarembó",
    aceptaMascotasOptions: "Sí",
    zona: "Tacuarembó",
    garaje: "Sí",
    m2Edificados: 150,
    m2Terreno: 10000,
    tipoDePropiedad: "Casa",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 1995,
    estado: "Buen estado",
    imgsrc: [
      "https://imgs.search.brave.com/5CZTzIEXYLsphb0ZDrPAB2-d3ljVVmFPh7mzNMb9IS8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90b3MtcHJlbWl1/bS9oZXJtb3NhLWNh/c2EtYXJxdWl0ZWN0/dXJhLW1pbmltYWxp/c3RhLWRpYS1zb2xl/YWRvXzIzMzY1LTE1/LmpwZz9zaXplPTYy/NiZleHQ9anBn",
      "https://example.com/image20.jpg",
      "https://example.com/image21.jpg",
    ],
  },
  {
    id: 8,
    title: "Apartamento en Malvín Norte",
    tipoMoneda: "U$D",
    precio: 1000,
    disposicion: "Contrafrente",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: ["Balcón", "Cocina Equipada", "Aire Acondicionado"],
    descripcion: "Amplio apartamento en Malvín Norte, cerca de la playa",
    aceptaMascotasOptions: "Sí",
    zona: "Malvín Norte",
    garaje: "Sí",
    m2Edificados: 90,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 2008,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/tomKas3SmcQnln40uT8h8oeGnRLOQXXWw3LD_WrIUHE/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9lc3Bh/Y2lvaG9nYXIuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDE2/LzA0LzUwLWZvdG9z/LWZhY2hhZGFzLWNh/c2FzLW1hcy1ib25p/dGFzLW1vZGVybmFz/LWRlbC1tdW5kby1j/YXNhLWRlLWVzdGls/by1mdXR1cmlzdGEt/Y29uLXRlamFkby1j/bGFzaWNvLTY0MHg0/NjYuanBn",
      "https://example.com/image23.jpg",
      "https://example.com/image24.jpg",
    ],
  },
  {
    id: 9,
    title: "Casa de playa en La Paloma",
    tipoMoneda: "U$D",
    precio: 1300,
    disposicion: "Frente al mar",
    tipoVenta: "Venta",
    ubicacion:  "Rocha",
    comodidades: ["Piscina", "Vista al mar", "Jardín amplio"],
    descripcion: "Hermosa casa de playa en La Paloma, frente al mar",
    aceptaMascotasOptions: "Sí",
    zona: "La Paloma",
    garaje: "Sí",
    m2Edificados: 180,
    m2Terreno: 800,
    tipoDePropiedad: "Casa",
    banos: 3,
    dormitorio: "4 dormitorios",
    anioConstruccion: 2013,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/6R4lSe51bTLHswDTXvf_OGYvlnlMLzeloYxYRe5G02Q/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuaG9taWZ5LmNv/bS9jX2ZpbGwsZl9h/dXRvLHFfYXV0byx3/Xzc0MC92MTQ4NzEw/NzE1Ny9wL3Bob3Rv/L2ltYWdlLzE4MzIy/MDQvSW50ZXJpb3Jf/Mi5qcGc",
      "https://example.com/image26.jpg",
      "https://example.com/image27.jpg",
    ],
  },
  {
    id: 10,
    title: "Apartamento en Carrasco",
    tipoMoneda: "U$D",
    precio: 1500,
    disposicion: "Frente al río",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: [
      "Balcón con vistas al río",
      "Cocina moderna",
      "Aire Acondicionado",
    ],
    descripcion: "Elegante apartamento en Carrasco, con vistas al río",
    aceptaMascotasOptions: "No",
    zona: "Carrasco",
    garaje: "Sí",
    m2Edificados: 110,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 2017,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/QNwbw9Faju0JkhmWQ9p9YNu88-wIAUVJQNVFFpDOlLM/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29uc3RydXllaG9n/YXIuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE2LzAyL0Nh/c2EtZGUtY2FtcG8t/ZGUtZG9zLXBpc29z/LURpc2UlQzMlQjFv/LXktZm90b3MtSHVu/dGVyLUxlZ2dpdHQt/U3R1ZGlvLTU2MHg0/MzIuanBn",
      "https://example.com/image29.jpg",
      "https://example.com/image30.jpg",
    ],
  },
  {
    id: 11,
    title: "Casa en las sierras",
    tipoMoneda: "U$D",
    precio: 950,
    disposicion: "Sierra",
    tipoVenta: "Venta",
    ubicacion: "Rocha",
    comodidades: [
      "Terreno amplio",
      "Vistas a las sierras",
      "Jardín con árboles",
    ],
    descripcion:
      "Encantadora casa en las Sierras de Rocha, rodeada de naturaleza",
    aceptaMascotasOptions: "Sí",
    zona: "Sierras de Rocha",
    garaje: "Sí",
    m2Edificados: 120,
    m2Terreno: 3000,
    tipoDePropiedad: "Casa",
    banos: 2,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2005,
    estado: "Buen estado",
    imgsrc: [
      "https://imgs.search.brave.com/YhT7J6_UhYBbnUOK4daCBM6NlREljKrCbwYDeFP-DJM/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTI5/NzU4NjE2Ni9lcy9m/b3RvL2ZvdG8tbW9k/ZXJuYS15LWVsZWdh/bnRlLWRlLWxhLWNv/Y2luYS5qcGc_cz02/MTJ4NjEyJnc9MCZr/PTIwJmM9enVNWVZk/em5GaGN4NWNzcGxi/c2FIRlJSTmRIeFht/YlJoSzZteTdlT2Q1/ND0",
      "https://example.com/image32.jpg",
      "https://example.com/image33.jpg",
    ],
  },
  {
    id: 12,
    title: "Piso en el Prado",
    tipoMoneda: "U$D",
    precio: 850,
    disposicion: "Frente al parque",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: [
      "Balcón con vistas al parque",
      "Cocina Equipada",
      "Aire Acondicionado",
    ],
    descripcion: "Amplio piso con vistas al Prado, junto al parque",
    aceptaMascotasOptions: "Sí",
    zona: "Prado",
    garaje: "Sí",
    m2Edificados: 100,
    m2Terreno: 0,
    tipoDePropiedad: "Piso",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 2010,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/56ihhTy1g1uN7PEXwwj1SnQkCXXhm00AVtq1lb_vJ0g/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90b3MtcHJlbWl1/bS9pbnRlcmlvci1t/b2Rlcm5vLWNhc2Et/YmxhbmNhXzE0NTY0/NC00Mjc4Mi5qcGc_/c2l6ZT02MjYmZXh0/PWpwZw",
      "https://example.com/image35.jpg",
      "https://example.com/image36.jpg",
    ],
  },
  {
    id: 13,
    title: "Casa en la costa de Rocha",
    tipoMoneda: "U$D",
    precio: 1100,
    disposicion: "Frente al mar",
    tipoVenta: "Venta",
    ubicacion: "Rocha",
    comodidades: ["Piscina", "Vista al mar", "Jardín con palmeras"],
    descripcion: "Espectacular casa frente al mar en la costa de Rocha",
    aceptaMascotasOptions: "Sí",
    zona: "Rocha",
    garaje: "Sí",
    m2Edificados: 160,
    m2Terreno: 1000,
    tipoDePropiedad: "Casa",
    banos: 3,
    dormitorio: "4 dormitorios",
    anioConstruccion: 2014,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/P_T7qpvErG5-DILNfZBLa89FneK6WmNu_iQbacaBI2s/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNDgw/Mjg4NjM0L2VzL2Zv/dG8vaGVybW9zYS1t/b2Rlcm5hLWNhc2Et/ZW4tZWwtYm9zcXVl/LXktYWwtYWlyZS1s/aWJyZS5qcGc_cz02/MTJ4NjEyJnc9MCZr/PTIwJmM9cDZFWlU2/SW54WFlfLUdKemk4/d0MxYjdROUtCT0xK/cnlSb1o4bF9FcHZD/MD0",
      "https://example.com/image38.jpg",
      "https://example.com/image39.jpg",
    ],
  },
  {
    id: 14,
    title: "Apartamento en Malvín Sur",
    tipoMoneda: "U$D",
    precio: 950,
    disposicion: "Contrafrente",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: [
      "Balcón con vistas al mar",
      "Cocina Equipada",
      "Aire Acondicionado",
    ],
    descripcion: "Moderno apartamento en Malvín Sur, a pasos de la playa",
    aceptaMascotasOptions: "No",
    zona: "Malvín Sur",
    garaje: "Sí",
    m2Edificados: 85,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2011,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/7dtItrHMAsd85IX7L672xw4jJKhooIheb041Iiq9occ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvNTIz/MzA3MzQ4L2VzL2Zv/dG8vYmFja3lhcmQt/d2l0aC1wb29sLW9m/LWNvbnRlbXBvcmFy/eS1ob3VzZS5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9ZHVI/aXNXNEdFeGRKS29i/ZUhXUHotbkV6aWFJ/Mng1azZqNkQweFpX/N1hCRT0",
      "https://example.com/image41.jpg",
      "https://example.com/image42.jpg",
    ],
  },
  {
    id: 15,
    title: "Casa en las sierras de Lavalleja",
    tipoMoneda: "U$D",
    precio: 1000,
    disposicion: "Sierra",
    tipoVenta: "Venta",
    ubicacion: "Lavalleja",
    comodidades: ["Terreno amplio", "Vistas a las sierras", "Piscina"],
    descripcion:
      "Hermosa casa en las Sierras de Lavalleja, rodeada de paz y naturaleza",
    aceptaMascotasOptions: "Sí",
    zona: "Sierras de Lavalleja",
    garaje: "Sí",
    m2Edificados: 140,
    m2Terreno: 5000,
    tipoDePropiedad: "Casa",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 2007,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/XjCGjtcpV4ouRFElXkQUehzk1xV7eqps5vZPevBI0I8/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29uc3RydXllaG9n/YXIuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE2LzAyL0hl/cm1vc2EtY2FzYS1k/ZS1jYW1wby1jb24t/cGllZHJhLXktbWFk/ZXJhLUhvdXNlcGxh/bnMuY29tLXYlQzMl/QURhLW5haWJhbm4u/Y29tXy01NjB4Mzcz/LmpwZw",
      "https://example.com/image44.jpg",
      "https://example.com/image45.jpg",
    ],
  },
  {
    id: 16,
    title: "Apartamento en Punta Carretas",
    tipoMoneda: "U$D",
    precio: 1200,
    disposicion: "Frente al mar",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: [
      "Balcón con vistas al mar",
      "Cocina moderna",
      "Aire Acondicionado",
    ],
    descripcion: "Espectacular apartamento en Punta Carretas con vistas al mar",
    aceptaMascotasOptions: "Sí",
    zona: "Punta Carretas",
    garaje: "Sí",
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2018,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/QlGOtUzENCHKWTUcp7f5iGMZeMhbn28f5pd4FOeufbE/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9kZWNv/cmFpZGVhcy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMTkv/MDgvMDMtNS03Njh4/NDk1LmpwZw",
      "https://example.com/image47.jpg",
      "https://example.com/image48.jpg",
    ],
  },
  {
    id: 17,
    title: "Casa en la costa de Canelones",
    tipoMoneda: "U$D",
    precio: 1100,
    disposicion: "Frente al mar",
    tipoVenta: "Venta",
    ubicacion: "Canelones",
    comodidades: ["Piscina", "Vista al mar", "Parque con palmeras"],
    descripcion:
      "Casa frente al mar en la costa de Canelones, ideal para relajarse",
    aceptaMascotasOptions: "Sí",
    zona: "Canelones",
    garaje: "Sí",
    m2Edificados: 160,
    m2Terreno: 800,
    tipoDePropiedad: "Casa",
    banos: 3,
    dormitorio: "4 dormitorios",
    anioConstruccion: 2015,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/AadNq3f67kj4YJ0l4A7cWBFwEMSnD8-tsbaUD884GMI/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29uc3RydXllaG9n/YXIuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE2LzAyL0Nh/c2EtZGUtY2FtcG8t/Y29uLWFkb2JlLUZv/dG9zLUdvbnphbG8t/QyVDMyVBMWNlcmVz/LURhbmN1YXJ0LURp/c2UlQzMlQjFvLU1h/cmluYS1WZWxsYS1B/cnF1aXRlY3Rvcy01/NjB4Mzc3LmpwZw",
      "https://example.com/image50.jpg",
      "https://example.com/image51.jpg",
    ],
  },
  {
    id: 18,
    title: "Apartamento en Buceo",
    tipoMoneda: "U$D",
    precio: 950,
    disposicion: "Frente al río",
    tipoVenta: "Alquiler",
    ubicacion: "Montevideo",
    comodidades: [
      "Balcón con vistas al río",
      "Cocina Equipada",
      "Aire Acondicionado",
    ],
    descripcion: "Moderno apartamento en Buceo, con hermosas vistas al río",
    aceptaMascotasOptions: "No",
    zona: "Buceo",
    garaje: "Sí",
    m2Edificados: 85,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "2 dormitorios",
    anioConstruccion: 2010,
    estado: "Excelente estado",
    imgsrc: [
      "https://imgs.search.brave.com/-1N1OHJLrWXcUODr40QmdP2x2VohTZf_EgDo_vkX7Ds/rs:fit:860:0:0/g:ce/aHR0cDovL2ltYWdl/cy5hcnF1aWRpY2Fz/LmNvbS5ici93cC1j/b250ZW50L3VwbG9h/ZHMvMjAxNS8wMi8x/MTE3Mjg0MC9jYXNh/LWdyZWdhLTEwMjR4/NzY4LmpwZw",
      "https://example.com/image53.jpg",
      "https://example.com/image54.jpg",
    ],
  },
  {
    id: 19,
    title: "Casa de playa en La Pedrera",
    tipoMoneda: "U$D",
    precio: 1300,
    disposicion: "Frente al mar",
    tipoVenta: "Venta",
    ubicacion: "Rocha",
    comodidades: ["Piscina", "Vista al mar", "Amplio jardín con palmeras"],
    descripcion:
      "Casa de playa en La Pedrera, con vistas al mar y mucha privacidad",
    aceptaMascotasOptions: "Sí",
    zona: "La Pedrera",
    garaje: "Sí",
    m2Edificados: 180,
    m2Terreno: 800,
    tipoDePropiedad: "Casa",
    banos: 3,
    dormitorio: "4 dormitorios",
    anioConstruccion: 2013,
    estado: "Excelente estado",
    imgsrc: [
      "https://decoraideas.com/wp-content/uploads/2019/08/01-8-768x427.jpg",
      "https://example.com/image56.jpg",
      "https://example.com/image57.jpg",
    ],
  },
  {
    id: 20,
    title: "Apartamento en Ciudad de la Costa",
    tipoMoneda: "U$D",
    precio: 1000,
    disposicion: "Frente al río",
    tipoVenta: "Alquiler",
    ubicacion: "Canelones",
    comodidades: [
      "Balcón con vistas al río",
      "Cocina moderna",
      "Aire Acondicionado",
    ],
    descripcion: "Amplio apartamento en Ciudad de la Costa, con vistas al río",
    aceptaMascotasOptions: "Sí",
    zona: "Ciudad de la Costa",
    garaje: "Sí",
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: "Apartamento",
    banos: 2,
    dormitorio: "3 dormitorios",
    anioConstruccion: 2017,
    estado: "Excelente estado",
    imgsrc: [
      "https://example.com/image58.jpg",
      "https://example.com/image59.jpg",
      "https://example.com/image60.jpg",
    ],
  },
];

export const ListadoLocalidades = [
  "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandu",
  "Río Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San José",
  "Soriano",
  "Tacuarembo",
  "Treinta y Tres",
];
export const ListadoTipoPropiedad = [
  "Casa",
  "Apartamento",
  "Terreno",
  "Local Comercial",
  "Oficina",
  "Chacra o Campo",
  "Garage o Cochera",
  "Negocio Especial",
  "Edificio",
  "Hotel",
  "Local industrial o galpón",
  "Otro",
];
export const ListadoCantidadDormitorios = [
  "Monoambiente",
  "1 dormitorio",
  "2 dormitorios",
  "3 dormitorios",
  "4 dormitorios",
  "5 dormitorios",
];
export const ListadoAtributos = [
  "Nombre",
  "Ubicacion",
  "Disposicion",
  "Año de Construccion",
  "M² edificados",
  "M² del terreno",
];
export const nombreDeGuardadoDeLosAtributos = [
  "title",
  "ubicacion",
  "disposicion",
  "anioConstruccion",
  "m2Edificados",
  "m2Terreno",
];
export const ListadotypesDeAtributos = [
  "text",
  "text",
  "text",
  "number",
  "number",
  "number",
];

export const ListadoBaños = ["1", "2", "3", "4", "5"];
export const ListadoOpciones = ["Si", "No"];
export const ListadoTipoDePublicacion = [
  "Alquiler",
  "Venta",
  "Alquiler Temporal",
];
export const ListadoMoneda = ["$", "U$D"];
export const ListadoDeEstado = [
  "Nuevo",
  "Usado",
  "En construccion",
  "Buen estado",
  "A estrenar",
  "Muy buen estado",
  "Excelente estado",
  "Sin construcción",
  "Otros",
];
export const ListadoComodidades = [
  "Piscina",
  "Garage",
  "Jardin",
  "Terraza",
  "Calefaccion",
  "Aire acondicionado",
  "Gimnasio",
  "Vista al mar",
  "Armarios empotrado",
  "Cocina equipada",
  "Chimenea",
  "Ascensor",
  "Lavandería",
  "Alarma de seguridad",
  "Sistema de videovigilancia",
  "Acceso para discapacitados",
  "Trastero",
  "Suelos de madera",
  "Sistema de riego automático",
  "Zona de barbacoa",
];
