export const ListadoPropiedades = [
    {
        id: 1,
        title: "Alquiler de monoambiente",
        tipoMoneda: "U$D",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
            "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 1,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
   ,
    },
    {
        id: 2,
        title: "Alquiler de apto",
        tipoMoneda: "U$D",
        precio: "1800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 1,
        dormitorio: 3,
        anioConstruccion: 2012,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 3,
        title: "Alquiler de Apartamento",
        tipoMoneda: "$U",
        precio: "24000",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 2,
        dormitorio: 2,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 4,
        title: "Venta de Casa",
        tipoMoneda: "U$D",
        precio: "120000",
        tipoVenta: "Venta",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "Casa",
        banos: 2,
        dormitorio: 3,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 5,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "18000",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "Casa",
        banos: 1,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 6,
        title: "Venta de Apto",
        tipoMoneda: "U$D",
        precio: "80000",
        tipoVenta: "Venta",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "Apartamento",
        banos: 1,
        dormitorio: 2,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 7,
        title: "Alquiler de Apto",
        tipoMoneda: "$U",
        precio: "22000",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "Apartamento",
        banos: 1,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 8,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 9,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 10,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 11,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 12,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 13,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },
    {
        id: 14,
        title: "Alquiler de monoambiente",
        tipoMoneda: "$U",
        precio: "800",
        tipoVenta: "Alquiler",
        ubicacion: ["Malvin", "Montevideo"],
        comodidades: ["Balcón", "Cochera",
        "Placard en cocina", "Aire Acondicionado", "Jardín"],
        descripcion: "",
        //Detalles de la Propiedad
        zona: "Capurro",
        m2Edificados: 288,
        m2Terreno: 267,
        tipoDePropiedad: "casa",
        banos: 3,
        dormitorio: 1,
        anioConstruccion: 2002,
        estado: "Requiere mantenimiento",
        imgsrc: ["https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_987.jpg", "https://cdn2.infocasas.com.uy/repo/img/th.outside750x811.122103_CW139153_874.jpg"]
    ,
    },

    
    ]
export const ListadoLocalidades = ['Artigas',
'Canelones',
'Cerro Largo',
'Colonia',
'Durazno',
'Flores',
'Florida',
'Lavalleja',
'Maldonado',
'Montevideo',
'Paysandu',
'Río Negro',
'Rivera',
'Rocha',
'Salto',
'San José',
'Soriano',
'Tacuarembo',
'Treinta y Tres',
]
export const ListadoTipoPropiedad = ['Casa',
'Apartamento',
'Terreno',
'Local Comercial',
'Oficina',
'Chacra o Campo',
'Garage o Cochera',
'Negocio Especial',
'Edificio',
'Hotel',
'Local industrial o galpón',
'Otro'
]
export const ListadoCantidadDormitorios = ['Monoambiente',
'1 dormitorio',
'2 dormitorios',
'3 dormitorios',
'4 dormitorios',
'5+ dormitorios'
]
export const ListadoBaños = ["1", "2", "3", "4", "5+"]
export const ListadoGarage = ["Si", "No"]
export const ListadoTipoDePublicacion = ['Alquiler', 'Venta', 'Alquiler Temporal']
export const ListadoMoneda = ["Pesos", "Dolares"]

    