export const ListadoPropiedades = [
        {
            id: 1,
            title: "Alquiler de monoambiente",
            tipoMoneda: "U$D",
            precio: 800,
            tipoVenta: "Alquiler",
            ubicacion: ["Malvin", "Montevideo"],
            comodidades: ["Balcón", "Cochera", "Placard en cocina", "Aire Acondicionado", "Jardín"],
            descripcion: "Encantador monoambiente en una excelente ubicación con hermosas vistas.",
            zona: "Capurro",
            m2Edificados: 288,
            m2Terreno: 267,
            tipoDePropiedad: "Apartamento",
            banos: 1,
            dormitorio: 1,
            anioConstruccion: 2002,
            estado: "Requiere mantenimiento",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 2,
            title: "Amplio apartamento en el centro",
            tipoMoneda: "U$D",
            precio: 1200,
            tipoVenta: "Alquiler",
            ubicacion: ["Centro", "Montevideo"],
            comodidades: ["Terraza", "Ascensor", "Cocina equipada", "Calefacción central"],
            descripcion: "Apartamento luminoso en el corazón de la ciudad, cerca de todos los servicios.",
            zona: "Centro",
            m2Edificados: 90,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2010,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 3,
            title: "Casa de campo con piscina",
            tipoMoneda: "U$D",
            precio: 250000,
            tipoVenta: "Venta",
            ubicacion: ["Las Piedras", "Canelones"],
            comodidades: ["Piscina", "Quincho", "Parque amplio", "Chimenea"],
            descripcion: "Hermosa casa de campo ideal para relajarse y disfrutar de la naturaleza.",
            zona: "Las Piedras",
            m2Edificados: 200,
            m2Terreno: 500,
            tipoDePropiedad: "Casa",
            banos: 3,
            dormitorio: 4,
            anioConstruccion: 1995,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 4,
            title: "Apartamento en la playa",
            tipoMoneda: "U$D",
            precio: 1800,
            tipoVenta: "Alquiler",
            ubicacion: ["Punta del Este", "Maldonado"],
            comodidades: ["Vista al mar", "Piscina comunitaria", "Amplio balcón", "Totalmente amueblado"],
            descripcion: "Elegante apartamento con vista al mar y acceso directo a la playa.",
            zona: "Punta del Este",
            m2Edificados: 120,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2015,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 5,
            title: "Casa familiar en el campo",
            tipoMoneda: "U$D",
            precio: 2000,
            tipoVenta: "Alquiler",
            ubicacion: ["Durazno", "Durazno"],
            comodidades: ["Jardín grande", "Parrillero", "Piscina privada", "Zona tranquila"],
            descripcion: "Amplia casa familiar en un entorno rural, ideal para escapar del ajetreo y el bullicio.",
            zona: "Durazno",
            m2Edificados: 250,
            m2Terreno: 5000,
            tipoDePropiedad: "Casa",
            banos: 3,
            dormitorio: 4,
            anioConstruccion: 1998,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 6,
            title: "Piso céntrico de lujo",
            tipoMoneda: "U$D",
            precio: 2500,
            tipoVenta: "Alquiler",
            ubicacion: ["Pocitos", "Montevideo"],
            comodidades: ["Terraza panorámica", "Gimnasio", "Seguridad 24/7", "Estacionamiento subterráneo"],
            descripcion: "Espectacular piso de lujo en una de las zonas más exclusivas de la ciudad.",
            zona: "Pocitos",
            m2Edificados: 300,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 3,
            dormitorio: 3,
            anioConstruccion: 2017,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 7,
            title: "Casa de playa con jacuzzi",
            tipoMoneda: "U$D",
            precio: 1800,
            tipoVenta: "Alquiler",
            ubicacion: ["La Paloma", "Rocha"],
            comodidades: ["Vista al mar", "Jacuzzi exterior", "Amplio jardín", "Chimenea"],
            descripcion: "Hermosa casa de playa con todas las comodidades para unas vacaciones inolvidables.",
            zona: "La Paloma",
            m2Edificados: 150,
            m2Terreno: 800,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2005,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 8,
            title: "Apartamento con vista al río",
            tipoMoneda: "U$D",
            precio: 1600,
            tipoVenta: "Alquiler",
            ubicacion: ["Carrasco", "Montevideo"],
            comodidades: ["Vista al río", "Piscina comunitaria", "Amplia terraza", "Seguridad 24/7"],
            descripcion: "Moderno apartamento con impresionantes vistas al río y comodidades de primer nivel.",
            zona: "Carrasco",
            m2Edificados: 110,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2014,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 9,
            title: "Casa rural con huerto",
            tipoMoneda: "U$D",
            precio: 1300,
            tipoVenta: "Alquiler",
            ubicacion: ["Colonia", "Colonia"],
            comodidades: ["Huerto ecológico", "Parrillero", "Piscina privada", "Tranquilidad absoluta"],
            descripcion: "Encantadora casa en el campo con un huerto orgánico y un entorno sereno.",
            zona: "Colonia",
            m2Edificados: 180,
            m2Terreno: 3000,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2000,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 10,
            title: "Apartamento céntrico con piscina",
            tipoMoneda: "U$D",
            precio: 1400,
            tipoVenta: "Alquiler",
            ubicacion: ["Ciudad Vieja", "Montevideo"],
            comodidades: ["Piscina en la azotea", "Gimnasio", "Estacionamiento", "Terraza con parrillero"],
            descripcion: "Moderno apartamento en el casco antiguo de la ciudad con piscina en la azotea.",
            zona: "Ciudad Vieja",
            m2Edificados: 80,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 1,
            dormitorio: 1,
            anioConstruccion: 2012,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 11,
            title: "Casa con piscina en la montaña",
            tipoMoneda: "U$D",
            precio: 1700,
            tipoVenta: "Alquiler",
            ubicacion: ["Minas", "Lavalleja"],
            comodidades: ["Piscina privada", "Amplio terreno", "Vistas panorámicas", "Chimenea"],
            descripcion: "Hermosa casa de montaña con piscina y vistas espectaculares.",
            zona: "Minas",
            m2Edificados: 220,
            m2Terreno: 4000,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2008,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 12,
            title: "Apartamento en zona residencial",
            tipoMoneda: "U$D",
            precio: 1100,
            tipoVenta: "Alquiler",
            ubicacion: ["Carrasco Norte", "Montevideo"],
            comodidades: ["Piscina comunitaria", "Gimnasio", "Seguridad 24/7", "Estacionamiento subterráneo"],
            descripcion: "Confortable apartamento en una tranquila zona residencial con comodidades de lujo.",
            zona: "Carrasco Norte",
            m2Edificados: 100,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2016,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 13,
            title: "Casa de playa en la costa",
            tipoMoneda: "U$D",
            precio: 1900,
            tipoVenta: "Alquiler",
            ubicacion: ["Piriápolis", "Maldonado"],
            comodidades: ["Vista al mar", "Piscina privada", "Amplio jardín", "Chimenea"],
            descripcion: "Encantadora casa de playa en la costa con todas las comodidades para el descanso.",
            zona: "Piriápolis",
            m2Edificados: 160,
            m2Terreno: 700,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2004,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 14,
            title: "Apartamento con vistas al río",
            tipoMoneda: "U$D",
            precio: 1750,
            tipoVenta: "Alquiler",
            ubicacion: ["Pocitos", "Montevideo"],
            comodidades: ["Vistas al río", "Piscina comunitaria", "Terraza amplia", "Seguridad 24/7"],
            descripcion: "Moderno apartamento con espectaculares vistas al río y comodidades de primera.",
            zona: "Pocitos",
            m2Edificados: 130,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2013,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 15,
            title: "Casa de campo con piscina",
            tipoMoneda: "U$D",
            precio: 1500,
            tipoVenta: "Alquiler",
            ubicacion: ["San José", "San José"],
            comodidades: ["Piscina privada", "Amplio terreno", "Vistas panorámicas", "Chimenea"],
            descripcion: "Encantadora casa de campo con piscina y vistas impresionantes.",
            zona: "San José",
            m2Edificados: 190,
            m2Terreno: 3500,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 4,
            anioConstruccion: 2006,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 16,
            title: "Apartamento en zona exclusiva",
            tipoMoneda: "U$D",
            precio: 2700,
            tipoVenta: "Alquiler",
            ubicacion: ["Carrasco", "Montevideo"],
            comodidades: ["Terraza panorámica", "Gimnasio", "Estacionamiento subterráneo", "Seguridad 24/7"],
            descripcion: "Espléndido apartamento en una de las zonas más exclusivas de la ciudad.",
            zona: "Carrasco",
            m2Edificados: 280,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 3,
            dormitorio: 3,
            anioConstruccion: 2018,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 17,
            title: "Casa de playa con vistas al mar",
            tipoMoneda: "U$D",
            precio: 200000,
            tipoVenta: "Venta",
            ubicacion: ["La Barra", "Maldonado"],
            comodidades: ["Vistas al mar", "Piscina privada", "Amplio jardín", "Chimenea"],
            descripcion: "Hermosa casa de playa con vistas al mar y todas las comodidades para unas vacaciones de ensueño.",
            zona: "La Barra",
            m2Edificados: 170,
            m2Terreno: 800,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2003,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 18,
            title: "Apartamento de diseño en el centro",
            tipoMoneda: "U$D",
            precio: 1900,
            tipoVenta: "Alquiler",
            ubicacion: ["Centro", "Montevideo"],
            comodidades: ["Diseño moderno", "Terraza amplia", "Estacionamiento subterráneo", "Seguridad 24/7"],
            descripcion: "Elegante apartamento con diseño contemporáneo en pleno centro de la ciudad.",
            zona: "Centro",
            m2Edificados: 120,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2016,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 19,
            title: "Casa rústica en el bosque",
            tipoMoneda: "U$D",
            precio: 1600,
            tipoVenta: "Alquiler",
            ubicacion: ["Maldonado", "Maldonado"],
            comodidades: ["Entorno natural", "Parrillero", "Piscina privada", "Chimenea"],
            descripcion: "Acogedora casa rústica en medio del bosque, perfecta para los amantes de la naturaleza.",
            zona: "Maldonado",
            m2Edificados: 140,
            m2Terreno: 3000,
            tipoDePropiedad: "Casa",
            banos: 2,
            dormitorio: 3,
            anioConstruccion: 2007,
            estado: "Buen estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        },
        {
            id: 20,
            title: "Apartamento con vistas al mar",
            tipoMoneda: "U$D",
            precio: 1750,
            tipoVenta: "Alquiler",
            ubicacion: ["Punta Carretas", "Montevideo"],
            comodidades: ["Vistas al mar", "Piscina comunitaria", "Terraza amplia", "Estacionamiento subterráneo"],
            descripcion: "Espectacular apartamento con impresionantes vistas al mar en una ubicación privilegiada.",
            zona: "Punta Carretas",
            m2Edificados: 160,
            m2Terreno: 0,
            tipoDePropiedad: "Apartamento",
            banos: 2,
            dormitorio: 2,
            anioConstruccion: 2015,
            estado: "Excelente estado",
            imgsrc: "https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW139153_47.jpg"
        }    
]
export const ListadoLocalidades = ['Artigas',
'Canelones',
'Cerro Largo',
'Colonia',
'Durazno',
'Flores',
'Florida',
'Lavalleja',
'Maldonado',
'Montevideo',
'Paysandu',
'Río Negro',
'Rivera',
'Rocha',
'Salto',
'San José',
'Soriano',
'Tacuarembo',
'Treinta y Tres',
]
export const ListadoTipoPropiedad = ['Casa',
'Apartamento',
'Terreno',
'Local Comercial',
'Oficina',
'Chacra o Campo',
'Garage o Cochera',
'Negocio Especial',
'Edificio',
'Hotel',
'Local industrial o galpón',
'Otro'
]
export const ListadoCantidadDormitorios = ['Monoambiente',
'1 dormitorio',
'2 dormitorios',
'3 dormitorios',
'4 dormitorios',
'5+ dormitorios'
]
export const ListadoBaños = ["1", "2", "3", "4", "5+"]
export const ListadoGarage = ["Si", "No"]
export const ListadoTipoDePublicacion = ['Alquiler', 'Venta', 'Alquiler Temporal']
export const ListadoMoneda = ["Pesos", "Dolares"]

    